[project]
name = "searxng-stealth-mcp"
version = "1.1.3"
description = "SearXNG Stealth MCP server for AI agents"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "requests"
]

[project.scripts]
searxng-stealth-mcp = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["main.py"]
